export { DEFAULT_ROLE_NAMES, type DefaultRoleName } from "./roles";

/**
 * Generated by `pnpm --filter @hpp/contracts generate:api-types`
 * (docs/28_OPENAPI_STRATEGY.md §1-2) against a live `apps/api` — never
 * hand-edited. Re-run whenever a DTO changes; a stale file only causes a
 * type mismatch at the frontend's next build, never a silent runtime drift.
 */
export type { components, paths, operations } from "./generated/api";
