/**
 * Default role→permission grants, transcribed from the docs/04_RBAC.md §2
 * summary table. This is the enforced source of truth the doc refers to
 * ("the seed data in role_permissions") — keep this in sync with that table
 * whenever either changes.
 *
 * "Own unit"/"own actions" row-level restrictions (Kepala Unit, Tim Costing)
 * are not expressed here — they're the same coarse-grained permission code as
 * the unrestricted version, narrowed at query time via
 * `user_hospital_memberships.scopedUnitId` (docs/04_RBAC.md §2 footnote),
 * which isn't enforceable yet since Sprint 3 hasn't added the cost/profit
 * center tables `scopedUnitId` will reference.
 */
export const DEFAULT_ROLE_NAMES = [
  "direktur",
  "cfo_finance_director",
  "tim_costing",
  "kepala_unit",
  "manajemen_medis",
  "system_admin",
] as const;

export type DefaultRoleName = (typeof DEFAULT_ROLE_NAMES)[number];

export const DEFAULT_ROLE_PERMISSIONS: Record<DefaultRoleName, string[]> = {
  direktur: [
    "organization.read",
    "hospital.read",
    "branch.read",
    "master_data.read",
    "cost_allocation.read",
    "profitability.read",
    "tariff.read",
    "doctor_analytics.read",
    "doctor_analytics.read_detail",
    "ai.use",
    "reports.read",
    "reports.export",
    "audit.read",
  ],
  cfo_finance_director: [
    "organization.read",
    "hospital.read",
    "branch.read",
    "master_data.read",
    "master_data.write",
    "upload.read",
    "cost_allocation.read",
    "cost_allocation.write",
    "profitability.read",
    "profitability.write",
    "tariff.read",
    "tariff.write",
    "tariff.approve",
    "doctor_analytics.read",
    "doctor_analytics.read_detail",
    "ai.use",
    "ai_proposal.approve",
    "reports.read",
    "reports.export",
    "reports.schedule",
    "audit.read",
    "period_closing.read",
  ],
  tim_costing: [
    "organization.read",
    "hospital.read",
    "branch.read",
    "master_data.read",
    "master_data.write",
    "upload.read",
    "upload.write",
    "cost_allocation.read",
    "cost_allocation.write",
    "profitability.read",
    "profitability.write",
    "tariff.propose",
    "doctor_analytics.read",
    "ai.use",
    "reports.read",
    "reports.export",
    "reports.schedule",
    "audit.read",
  ],
  kepala_unit: [
    "organization.read",
    "hospital.read",
    "branch.read",
    "master_data.read",
    "cost_allocation.read",
    "profitability.read",
    "doctor_analytics.read",
    "ai.use",
    "reports.read",
    "reports.export",
  ],
  manajemen_medis: [
    "organization.read",
    "hospital.read",
    "branch.read",
    "master_data.read",
    "profitability.read",
    "doctor_analytics.read",
    "doctor_analytics.read_detail",
    "ai.use",
    "reports.read",
    "reports.export",
  ],
  system_admin: [
    "organization.read",
    "organization.write",
    "hospital.read",
    "hospital.write",
    "branch.read",
    "branch.write",
    "master_data.read",
    "master_data.write",
    "upload.read",
    "upload.write",
    "cost_allocation.read",
    "cost_allocation.write",
    "profitability.read",
    "profitability.write",
    "tariff.read",
    "tariff.write",
    "doctor_analytics.read",
    "doctor_analytics.read_detail",
    "rbac.read",
    "rbac.write",
    "reports.read",
    "reports.export",
    "reports.schedule",
    "audit.read",
    "period_closing.read",
    "period_closing.write",
  ],
};
